name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # Debian-based system

    steps:
    - uses: actions/checkout@v4

    # - name: Install system dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y \
    #       libgl1-mesa-glx \
    #       libsm6 \
    #       libxext6 \
    #       libxrender-dev

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#        pip install pytest opencv-python-headless

    - name: Run tests
      env:
        TEST_IMAGE_PATH: tests/test_image.jpg
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v tests/test_weapon_detector.py

    - name: Cleanup test artifacts
      run: |
        rm -f tests/output.jpg